version: "3"

services:
    app:
        environment:
            - APACHE_RUN_USER=#1000
        build:
            context: ./docker
        depends_on:
            -   laravel
        ports:
            - 1000:80
        volumes:
            - ./:/var/www/html
        networks:
            - mynet
    laravel:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: laravel
        ports:
            - 5433:5432
networks:
    mynet:
        driver: bridge