version: "3"

services:
    app:
        environment:
            - APACHE_RUN_USER=#1000
        build:
            context: ./apache-image
        depends_on:
            -   laravel
        ports:
            - 1000:80
        volumes:
            - ./laravel:/var/www/html
    laravel:
        image: mysql
        environment:
            MYSQL_DATABASE: apteka
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3307:3306
        container_name: myDB